def process_exception(exception, request=None, message_user=False):
    pass
